services:
  db:
    image: postgres:latest
    container_name: tasks-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    volumes:
      - ./tasks.sql:/docker-entrypoint-initdb.d/tasks.sql
    ports:
      - "5432:5432"