name: Deploy Go App on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push to Docker Hub Repository
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sevvyp/tasks_v1:latest

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_INSTANCE_IP_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV}}
          script: |
            docker stop tasks_v1 || true
            docker rm tasks_v1 || true
            sudo rm /etc/tasks_v1/config.json || true
            sudo mkdir /etc/tasks_v1 || true
            sudo touch /etc/tasks_v1/config.json
            sudo chmod 777 /etc/tasks_v1/config.json
            sudo echo "${{ secrets.DEV_CONFIG_FILE }}" > /etc/tasks_v1/config.json
            sudo chmod 644 /etc/tasks_v1/config.json
            docker pull sevvyp/tasks_v1:latest
            docker run -d -p 8080:8080 -v /etc/tasks_v1/config.json:/etc/tasks_v1/config.json --name tasks_v1 sevvyp/tasks_v1:latest
